### ISSUE TITLE
Symmetries requiring square grids fail with "SquareWorldError"

### ISSUE THREAD

**Issue by apaap** [AlephAlpha/rlifesrc#2]
Using latest master:
`$ cargo run 10 10 2 --symmetry 'D2\'`

Output:
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SquareWorldError', tui/src/args.rs:316:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

Symmetries C4, D2/, D4X, and D8 give same error.
Transforms R90, R270, F/, and F\ also give same error.

v0.3.3 works as expected.

**Comment by AlephAlpha** [comment]
Thank you. I made a very stupid mistake. Fixed.

**Comment by apaap** [comment]
Thank you, works great once again.
